# Build Stage
FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/jdblog/package*.json ./
RUN npm install
COPY frontend/jdblog/. .
RUN npm run build
 
# Production Stage
FROM nginx:stable-alpine AS production
COPY --from=build /app/dist /usr/share/nginx/html
COPY frontend/nginx_default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
